### Create contact
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
  "contact3": {
    "firstName": "Austin",
    "lastName": "Wedel",
    "email": "wedelsthebest@test.com",
    "favoriteColor": "Orange",
    "birthday": "04/25/93"
  }
}

### Update contact (Replace ID with a real one)
PUT http://localhost:8080/contacts/645123abc456def789012345 HTTP/1.1
content-type: application/json

{
    "firstName":"Derek",
    "lastName":"Wedel",
    "email":"derekW@test.com",
    "favoriteColor":"Burgundy",
    "birthday":"09/28/1995"
}

### Delete contact (Replace ID with a real one)
DELETE http://localhost:8080/contacts/645123abc456def789012345 HTTP/1.1
